[build]
  command = "cd alpizzificio && npm install && npm run build"
  publish = "alpizzificio/dist/alpizzificio/browser"

[build.environment]
  NODE_VERSION = "24"

[dev]
  publish = "alpizzificio/dist/alpizzificio/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
