[build]
  command = "cd alpizzificio && npx ng build --configuration production"
  publish = "dist/alpizzificio/browser"

[build.environment]
  NODE_VERSION = "18"

[dev]
  publish = "dist/alpizzificio/browser"
